version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: education1999991
      MYSQL_ROOT_PASSWORD: root_password  # Specify a password instead of an empty string
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # If you wish to allow an empty password, otherwise remove this line
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/education1999991
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password  # Make sure the same password is used here
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
